import type { Trend } from "../../types";

// t4 Fragmentation, t9 Bridge States, t13 Chinese Overcapacity Wave.

export const GEOPOLITICS_TRENDS: Trend[] = [
  {
    id: "t4",
    name: "Geopolitical Fragmentation",
    stage: 2,
    horizon: "2-4 years",
    confidence: 75,
    description: "World splitting into blocs, reshoring supply chains, weaponizing trade and finance. European NATO spend on structural path from 2% → 3.5% → 5% of GDP.",
    subTrends: ["Nearshoring boom", "Defense surge", "Semiconductor sovereignty", "Rare earth chains"],
    signals: [],
    thesis: "Defense and reshoring capex larger and longer than expected.",
    bearCase: "Reshoring is inflationary fantasy. Capital forces detente.",
    investmentMap: "Long: EUDF (defence), RHM.DE, BA.L, LHX, NOC, LMT, RTX, RARE (strategic metals), MP, ASML, AMAT.",
    mispricingScore: 55,
    benchmarkTicker: "EUDF",
    invalidationMetric: {
      name: "EU NATO aggregate defense spend / GDP",
      threshold: "< 2.5% trailing 12M",
      direction: "below",
      source: "NATO annual report",
    },
  },
  {
    id: "t9",
    name: "Strategic Bridge States",
    stage: 1,
    horizon: "2-5 years",
    confidence: 78,
    description: "Countries at nexus of green energy, nearshoring, digital transformation bridge competing blocs.",
    subTrends: ["Green hydrogen export", "Nearshoring corridors", "Phosphates-to-LFP", "Renewable infra"],
    signals: [],
    thesis: "Bridge states capture asymmetric value in a fragmenting world.",
    bearCase: "Protectionism blocks exports. Political instability.",
    investmentMap: "Frontier/EM: Schroder Frontier Markets, XSOE. Vietnam: VNM. India: INDA. Mexico: EWW.",
    mispricingScore: 82,
    benchmarkTicker: "EWW",
    invalidationMetric: {
      name: "US tariff regime on Mexico / Vietnam imports",
      threshold: "blanket >20% tariff for 6 months",
      direction: "cross",
      source: "USTR, Federal Register",
    },
  },
  {
    id: "t13",
    name: "Chinese Overcapacity Export Wave",
    stage: 2,
    horizon: "2-4 years",
    confidence: 82,
    description: "China's domestic demand collapse meets industrial-policy overbuild in EVs, solar, batteries, steel, chemicals. Export surge deflates Western consumer goods but kills incumbent producers. Response: tariffs + anti-dumping + reshoring.",
    subTrends: ["EV dumping", "Solar panel flood", "Steel/chemicals glut", "Western industrial restructure"],
    signals: [],
    thesis: "Long reshoring beneficiaries + tariff-protected Western industrials; short exposed European autos/chems + emerging-market incumbents. Disinflationary for consumer prices, deflationary for Western industrial margins.",
    bearCase: "Detente + managed overcapacity via Chinese property stimulus. Tariffs never stick.",
    investmentMap: "Long tariff winners: NUE, STLD (US steel), ETN, ROK. Short EU exposed: bear certificates on VOW3.DE (VW), STLA (Stellantis), BAS.DE (BASF). Long US consumer staples with pricing power: COST, WMT.",
    mispricingScore: 68,
    benchmarkTicker: "NUE",
    invalidationMetric: {
      name: "China industrial capacity utilization (NBS)",
      threshold: "> 78% for 2 quarters",
      direction: "above",
      source: "China National Bureau of Statistics",
    },
  },
];
