import type { Trend } from "../../types";

// t2 Debasement, t7 Commodities Financialization, t14 Housing Affordability.

export const MACRO_TRENDS: Trend[] = [
  {
    id: "t2",
    name: "Financial Repression & Fiat Debasement",
    stage: 0,
    horizon: "3-7 years",
    confidence: 75,
    description: "Central banks impose yield curve control, forced bond-buying, stealth inflation to liquidate debt.",
    subTrends: ["Dollar erosion", "Gold remonetization", "Bitcoin as digital gold", "BRICS settlement", "Negative real yields"],
    signals: [],
    thesis: "Decade of negative real yields. Long hard assets vs. short long-duration bonds.",
    bearCase: "Financial repression WORKS. No tradeable crisis event.",
    investmentMap: "Long: WGLD (gold 0.12%), WSLV (silver), IBIT (Bitcoin), ITPS (TIPS), GDX/GDXJ (gold miners). Gold overweight implicitly expresses short-bonds view.",
    mispricingScore: 82,
    benchmarkTicker: "WGLD",
    invalidationMetric: {
      name: "10Y TIPS real yield (FRED DFII10)",
      threshold: "> 2.5% for 6 months",
      direction: "above",
      source: "FRED",
    },
  },
  {
    id: "t7",
    name: "Commodities Financialization",
    stage: 2,
    horizon: "2-4 years",
    confidence: 80,
    description: "Hard assets becoming monetary reserves. Central banks hoarding gold; extends to silver, copper, uranium. Tokenization on-chain (PAXG, XAUT) expanding the addressable demand pool.",
    subTrends: ["Central bank gold buying", "Silver premium", "Uranium reserves", "Copper as collateral", "Real-world assets on-chain"],
    signals: [],
    thesis: "Commodities remonetized. Physical ETCs have no equity beta; miners do. On-chain wrappers add a new bid.",
    bearCase: "Digital assets absorb alternative reserve demand. Central banks reverse buying.",
    investmentMap: "Physical: WGLD, WSLV, SPUT, OD7C. Miners: GDX, RARE, WNUC. Individual: GOLD (Barrick), FCX (Freeport). Broad: WTIC. Tokenized: PAXG, XAUT.",
    mispricingScore: 72,
    benchmarkTicker: "WGLD",
    invalidationMetric: {
      name: "Central-bank net gold purchases (WGC, trailing 12M)",
      threshold: "< 500 tonnes for 2 consecutive years",
      direction: "below",
      source: "World Gold Council",
    },
  },
  {
    id: "t14",
    name: "Housing Affordability Crisis",
    stage: 2,
    horizon: "3-7 years",
    confidence: 78,
    description: "Boomer-owned housing stock meets millennial/gen-Z formation demand. Rate-locked supply, underbuilt decade, AI-displaced wages. Political response = forced release (inheritance tax, vacancy tax, YIMBY zoning) or structural rent-seeking.",
    subTrends: ["Build-to-rent", "Zoning liberalization", "Boomer downsize wave", "Mortgage rate-lock unwind"],
    signals: [],
    thesis: "Homebuilders and multifamily operators capture the shortage. Short rate-sensitive REITs in repression regime.",
    bearCase: "Remote work permanently disperses demand; demographic formation slows faster than supply constraint. Rates stay high, construction stalls.",
    investmentMap: "Long US builders: LEN, DHI, NVR. Long multifamily: AVB, EQR. Long construction materials: VMC, MLM. Avoid: rate-sensitive REITs (O, STAG). EU proxy: EPRA Europe ETF, Vonovia (VNA.DE).",
    mispricingScore: 70,
    benchmarkTicker: "LEN",
    invalidationMetric: {
      name: "US housing starts / household formation ratio",
      threshold: "> 1.2 for 3 consecutive quarters",
      direction: "above",
      source: "Census Bureau",
    },
  },
];
