import type { Trend } from "../../types";

// t1 AI & AGI, t6 Trust/Verification, t8 Synthetic Biology.

export const TECH_TRENDS: Trend[] = [
  {
    id: "t1",
    name: "AI & AGI Disruption",
    stage: 2,
    horizon: "1-3 years",
    confidence: 85,
    description: "AI automating knowledge work. Trough of disillusionment as enterprise ROI disappoints, but infra buildout continues.",
    subTrends: ["AI infrastructure", "Knowledge worker displacement", "Enterprise ROI reckoning", "Open-source commoditization"],
    signals: [],
    thesis: "Infra buildout durable. Long picks-and-shovels, short AI-wrapper SaaS.",
    bearCase: "AI infra is massive capital misallocation. Incumbents integrate open-source, crushing challengers.",
    investmentMap: "Long: NVDA, AVGO, TSM, GOOG, AMZN, MSFT, GEV. Short: Bear certificates on Nasdaq via Avanza Markets. PRIIPs blocks all US inverse ETFs for EU investors.",
    mispricingScore: 68,
    benchmarkTicker: "NVDA",
    invalidationMetric: {
      name: "Hyperscaler AI capex / AI revenue ratio (MSFT+GOOG+META+AMZN)",
      threshold: "> 3x for 2 consecutive quarters",
      direction: "above",
      source: "10-Qs, press releases",
    },
  },
  {
    id: "t6",
    name: "Trust Crisis & Verification Economy",
    stage: 1,
    horizon: "1-3 years",
    confidence: 80,
    description: "AI synthetic content makes truth premium. Zero-trust drives verification investment.",
    subTrends: ["Digital identity", "Content provenance", "Deepfake detection", "Zero-trust security"],
    signals: [],
    thesis: "Verification becomes critical infrastructure.",
    bearCase: "Big tech solves verification internally.",
    investmentMap: "Long: W1TB (cybersecurity), CRWD, PANW, FTNT, ZS, OKTA, CYBR, Chainlink (LINK).",
    mispricingScore: 75,
    benchmarkTicker: "W1TB",
    invalidationMetric: {
      name: "C2PA / content-provenance adoption by top-5 platforms",
      threshold: "all 5 ship native provenance UI",
      direction: "cross",
      source: "Platform changelogs",
    },
  },
  {
    id: "t8",
    name: "Synthetic Biology",
    stage: 0,
    horizon: "7-12 years",
    confidence: 65,
    description: "AI-powered genomics enabling bio-manufacturing of chemicals, materials, medicines.",
    subTrends: ["AI drug discovery", "Precision fermentation", "Personalized medicine"],
    signals: [],
    thesis: "AI + biology is generational. Watch food/materials before pharma.",
    bearCase: "Bio-manufacturing perpetually five years away.",
    investmentMap: "Long: CRSP, NTLA, DNA (Ginkgo), TWST, RXRX, IXJ (healthcare exposure). Nascent: 1-3% max.",
    mispricingScore: 80,
    benchmarkTicker: "CRSP",
    invalidationMetric: {
      name: "First FDA-approved AI-designed therapeutic at commercial scale",
      threshold: "approval + >$500M annual revenue",
      direction: "cross",
      source: "FDA orange book, company filings",
    },
  },
];
