import type { Trend } from "../types";

const TRENDS_1_5: Trend[] = [
  { id: "t1", name: "AI & AGI Disruption", stage: 2, horizon: "1-3 years", confidence: 85,
    description: "AI automating knowledge work. Trough of disillusionment as enterprise ROI disappoints, but infra buildout continues.",
    subTrends: ["AI infrastructure", "Knowledge worker displacement", "Enterprise ROI reckoning", "Open-source commoditization"],
    signals: [],
    thesis: "Infra buildout durable. Long picks-and-shovels, short AI-wrapper SaaS.",
    bearCase: "AI infra is massive capital misallocation. Incumbents integrate open-source, crushing challengers.",
    investmentMap: "Long: NVDA, AVGO, TSM, GOOG, AMZN, MSFT, GEV. Short: Bear certificates on Nasdaq via Avanza Markets. PRIIPs blocks all US inverse ETFs for EU investors.",
    mispricingScore: 68, benchmarkTicker: "NVDA" },
  { id: "t2", name: "Financial Repression & Fiat Debasement", stage: 0, horizon: "3-7 years", confidence: 75,
    description: "Central banks impose yield curve control, forced bond-buying, stealth inflation to liquidate debt.",
    subTrends: ["Dollar erosion", "Gold remonetization", "Bitcoin as digital gold", "BRICS settlement", "Negative real yields"],
    signals: [],
    thesis: "Decade of negative real yields. Long hard assets vs. short long-duration bonds.",
    bearCase: "Financial repression WORKS. No tradeable crisis event.",
    investmentMap: "Long: WGLD (gold 0.12%), WSLV (silver), IBIT (Bitcoin), GDX/GDXJ (gold miners). Gold overweight implicitly expresses short-bonds view.",
    mispricingScore: 82, benchmarkTicker: "WGLD" },
  { id: "t3", name: "Climate Acceleration & Energy Transition", stage: 2, horizon: "5-10 years", confidence: 80,
    description: "Climate change accelerating, forcing emergency energy transition and massive infrastructure spend.",
    subTrends: ["Nuclear renaissance", "Grid modernization", "Climate migration", "Copper supercycle"],
    signals: [],
    thesis: "Market prices orderly transition; reality is chaotic. Nuclear and copper mispriced.",
    bearCase: "Solar + battery cost crash makes micro-grids bypass centralized overhauls.",
    investmentMap: "Long: SPUT (physical uranium), WNUC (miners), CCJ, NXE, OD7C (copper), GEV, BWXT, PWR, ETN. Short: Coastal REITs.",
    mispricingScore: 65, benchmarkTicker: "SPUT" },
  { id: "t4", name: "Geopolitical Fragmentation", stage: 2, horizon: "2-4 years", confidence: 75,
    description: "World splitting into blocs, reshoring supply chains, weaponizing trade and finance.",
    subTrends: ["Nearshoring boom", "Defense surge", "Semiconductor sovereignty", "Rare earth chains"],
    signals: [],
    thesis: "Defense and reshoring capex larger and longer than expected.",
    bearCase: "Reshoring is inflationary fantasy. Capital forces detente.",
    investmentMap: "Long: EUDF (defence), RHM.DE, BA.L, LHX, NOC, RARE (strategic metals), MP, ASML, AMAT.",
    mispricingScore: 55, benchmarkTicker: "RARE" },
  { id: "t5", name: "Demographic Inversion", stage: 2, horizon: "3-8 years", confidence: 90,
    description: "Population decline in China, Korea, Japan, Germany. Labor shortages forcing automation.",
    subTrends: ["Automation as labor substitute", "Healthcare explosion", "Pension erosion"],
    signals: [],
    thesis: "Demographics force AI/automation adoption. Long automation, long healthcare.",
    bearCase: "Productivity renaissance OFFSETS demographic drag.",
    investmentMap: "Long: Wellington HC fund, IXJ, UNH, LLY, ISRG, ROBO ETF, Fanuc (6954.T), ROK.",
    mispricingScore: 70, benchmarkTicker: "IXJ" },
];

const TRENDS_6_10: Trend[] = [
  { id: "t6", name: "Trust Crisis & Verification Economy", stage: 1, horizon: "1-3 years", confidence: 80,
    description: "AI synthetic content makes truth premium. Zero-trust drives verification investment.",
    subTrends: ["Digital identity", "Content provenance", "Deepfake detection", "Zero-trust security"],
    signals: [],
    thesis: "Verification becomes critical infrastructure.",
    bearCase: "Big tech solves verification internally.",
    investmentMap: "Long: W1TB (cybersecurity), CRWD, PANW, FTNT, ZS, OKTA, CYBR, Chainlink (LINK).",
    mispricingScore: 75, benchmarkTicker: "W1TB" },
  { id: "t7", name: "Commodities Financialization", stage: 2, horizon: "2-4 years", confidence: 80,
    description: "Hard assets becoming monetary reserves. Central banks hoarding gold; extends to silver, copper, uranium.",
    subTrends: ["Central bank gold buying", "Silver premium", "Uranium reserves", "Copper as collateral"],
    signals: [],
    thesis: "Commodities remonetized. Physical ETCs have no equity beta; miners do.",
    bearCase: "Digital assets absorb alternative reserve demand.",
    investmentMap: "Physical: WGLD, WSLV, SPUT, OD7C. Miners: GDX, RARE, WNUC. Individual: GOLD (Barrick), FCX (Freeport). Broad: WTIC.",
    mispricingScore: 72, benchmarkTicker: "WGLD" },
  { id: "t8", name: "Synthetic Biology", stage: 0, horizon: "7-12 years", confidence: 65,
    description: "AI-powered genomics enabling bio-manufacturing of chemicals, materials, medicines.",
    subTrends: ["AI drug discovery", "Precision fermentation", "Personalized medicine"],
    signals: [],
    thesis: "AI + biology is generational. Watch food/materials before pharma.",
    bearCase: "Bio-manufacturing perpetually five years away.",
    investmentMap: "Long: CRSP, NTLA, DNA (Ginkgo), TWST, RXRX, IXJ (healthcare exposure). Nascent: 1-3% max.",
    mispricingScore: 80, benchmarkTicker: "CRSP" },
  { id: "t9", name: "Strategic Bridge States", stage: 1, horizon: "2-5 years", confidence: 78,
    description: "Countries at nexus of green energy, nearshoring, digital transformation bridge competing blocs.",
    subTrends: ["Green hydrogen export", "Nearshoring corridors", "Phosphates-to-LFP", "Renewable infra"],
    signals: [],
    thesis: "Bridge states capture asymmetric value in a fragmenting world.",
    bearCase: "Protectionism blocks exports. Political instability.",
    investmentMap: "Frontier/EM: Schroder Frontier Markets, XSOE. Vietnam: VNM. India: INDA. Mexico: EWW.",
    mispricingScore: 82, benchmarkTicker: "EWW" },
  { id: "t10", name: "Carbon as Feedstock", stage: 0, horizon: "8-15 years", confidence: 55,
    description: "Cheap energy makes CO2 capture economical, turning carbon into manufacturing input.",
    subTrends: ["Direct air capture", "Synthetic hydrocarbons", "Carbon materials"],
    signals: [],
    thesis: "Breaks climate doom loop. When capture below $100/ton, economics flip.",
    bearCase: "Energy costs never drop enough.",
    investmentMap: "Long (speculative): OXY (1PointFive DAC), PLUG, NEL.OL, ITM.L, WCO2 (carbon ETC). Monitor only.",
    mispricingScore: 85, benchmarkTicker: "OXY" },
];

export const SEED_TRENDS: Trend[] = [...TRENDS_1_5, ...TRENDS_6_10];
