import type { CrashWatchItem } from "../types";

export const CRASH_WATCHLIST: CrashWatchItem[] = [
  { ticker: "ASML", name: "ASML Holding", sector: "Semicon Equipment", trends: ["t1","t4"],
    quality: "Absolute monopoly on EUV lithography. 50%+ margins. $36B+ backlog.",
    now: "$1,500", high: "$1,100", offHigh: "+36%", buyZone: "-50 to -60%", buyPrice: "$440-550", maxPos: "3-5%" },
  { ticker: "TSM", name: "TSMC", sector: "Foundry", trends: ["t1","t4","t3"],
    quality: "Makes ALL advanced chips. Monopoly on 3nm/2nm. 55%+ margins.",
    now: "$370", high: "$222 (pre-split ref)", offHigh: "Near ATH", buyZone: "Wait for -40%+", buyPrice: "$190-210", maxPos: "3-5%" },
  { ticker: "NVDA", name: "NVIDIA", sector: "Semiconductors", trends: ["t1","t3","t5"],
    quality: "CUDA lock-in. 75%+ gross margins. Every AI workload needs GPUs.",
    now: "$189", high: "$212", offHigh: "-11%", buyZone: "-45 to -55%", buyPrice: "$95-115", maxPos: "3-5%" },
  { ticker: "AVGO", name: "Broadcom", sector: "Semiconductors", trends: ["t1","t3","t4"],
    quality: "Custom AI chips + VMware. Diversified. 60%+ margins.",
    now: "$380", high: "$305", offHigh: "+25%", buyZone: "Wait for -40%+", buyPrice: "$180-210", maxPos: "3-5%" },
  { ticker: "GEV", name: "GE Vernova", sector: "Grid & Nuclear", trends: ["t3","t1","t5"],
    quality: "Grid equipment + nuclear turbines. AI needs grid regardless of software ROI.",
    now: "$991", high: "$948", offHigh: "+5%", buyZone: "-40 to -50%", buyPrice: "$475-570", maxPos: "2-4%" },
  { ticker: "ETN", name: "Eaton Corp", sector: "Electrical Infra", trends: ["t3","t1","t4"],
    quality: "Data center power, EV charging, grid. Decades of dividend growth.",
    now: "$404", high: "$408", offHigh: "-1%", buyZone: "-35 to -45%", buyPrice: "$225-265", maxPos: "2-4%" },
  { ticker: "PWR", name: "Quanta Services", sector: "Grid Construction", trends: ["t3","t1"],
    quality: "Builds actual grid. Massive labor moat. $44B backlog.",
    now: "$596", high: "$584", offHigh: "+2%", buyZone: "Wait for -40%+", buyPrice: "$290-350", maxPos: "2-3%" },
  { ticker: "BWXT", name: "BWX Technologies", sector: "Nuclear Components", trends: ["t3","t4","t1"],
    quality: "Only US full nuclear fuel fabrication. Navy + commercial. Defense monopoly.",
    now: "$233", high: "$230", offHigh: "+1%", buyZone: "-35 to -45%", buyPrice: "$127-150", maxPos: "2-3%" },
  { ticker: "FCX", name: "Freeport-McMoRan", sector: "Copper Mining", trends: ["t3","t7","t4","t1"],
    quality: "World's largest copper producer. Grasberg mine. Low-cost.",
    now: "$68", high: "$55", offHigh: "+24%", buyZone: "-45 to -55%", buyPrice: "$25-30", maxPos: "2-4%" },
  { ticker: "OKLO", name: "Oklo Inc", sector: "Micro-Reactors", trends: ["t1","t3"],
    quality: "SPECULATIVE. Pre-revenue. NRC denied first license. Zero working reactors.",
    now: "$54", high: "$194", offHigh: "-72%", buyZone: "Already crashed. Need regulatory catalyst.", buyPrice: "$20-30 with catalyst", maxPos: "0.5-1%" },
  { ticker: "NBIS", name: "Nebius Group", sector: "AI Cloud Infra", trends: ["t1","t3"],
    quality: "SPECULATIVE. $27B Meta deal but $596M loss, $16-20B capex, massive dilution.",
    now: "$155", high: "$141", offHigh: "+10%", buyZone: "-55 to -65%", buyPrice: "$50-55", maxPos: "1-2%" },
];
