import type { Position } from "../../types";

// Tier 1: Physical commodities + inflation-linked bonds. Anti-correlated to equities.
// Deploy now regardless of regime.

export const TIER_1: Position[] = [
  {
    tier: 1,
    dir: "LONG",
    ticker: "SPUT",
    name: "HANetf Sprott Physical Uranium ETC",
    type: "Physical",
    fee: "1.48% all-in",
    trends: ["t3", "t7", "t1"],
    conv: 95,
    why: "Sprott buys physical yellowcake at premium. Tightens supply. $86/lb, structural deficit.",
    when: "Buy now",
    status: "GO",
    corr: "Anti-correlated",
  },
  {
    tier: 1,
    dir: "LONG",
    ticker: "OD7C",
    name: "WisdomTree Copper ETC",
    type: "Physical",
    fee: "0.49%",
    trends: ["t3", "t4", "t7", "t1", "t11"],
    conv: 90,
    why: "At intersection of more trends than any asset. No new mines until 2028+. Water/energy/AI convergence.",
    when: "Buy now",
    status: "GO",
    corr: "Anti-correlated",
  },
  {
    tier: 1,
    dir: "LONG",
    ticker: "WGLD",
    name: "WisdomTree Core Physical Gold",
    type: "Physical",
    fee: "0.12%",
    trends: ["t2", "t7"],
    conv: 85,
    why: "Financial repression hedge. 0.12% strictly superior to VZLD (0.39%). Corrected 20%.",
    when: "Accumulate on dips",
    status: "APPROACHING",
    corr: "Anti-correlated",
  },
  {
    tier: 1,
    dir: "LONG",
    ticker: "WSLV",
    name: "WisdomTree Core Physical Silver",
    type: "Physical",
    fee: "0.19%",
    trends: ["t2", "t7", "t3"],
    conv: 82,
    why: "Dual monetary + industrial (solar). Corrected 32%. Bigger upside in crisis.",
    when: "Accumulate",
    status: "APPROACHING",
    corr: "Anti-correlated",
  },
  {
    tier: 1,
    dir: "LONG",
    ticker: "ITPS",
    name: "iShares $ TIPS UCITS ETF (GBP Hedged)",
    type: "Inflation-linked bonds",
    fee: "0.10%",
    trends: ["t2", "t15"],
    conv: 82,
    why: "The literal instrument for the debasement + wage-price thesis. Pays real yield + CPI accretion. Zero equity beta, no miner risk. EU UCITS alternative to TIP (US).",
    when: "Buy now (real yields >1.5% is a gift)",
    status: "GO",
    corr: "Anti-correlated",
  },
];
