import type { Position } from "../../types";

// Tier 2: Sector ETFs + miners. Equity beta. Deploy on correction (VIX>25 or -15% drawdown).

export const TIER_2: Position[] = [
  {
    tier: 2,
    dir: "LONG",
    ticker: "WNUC",
    name: "WisdomTree Uranium & Nuclear",
    type: "Sector ETF",
    fee: "0.47%",
    trends: ["t3", "t7", "t1"],
    conv: 88,
    why: "Broader nuclear incl. GE Vernova, Curtiss-Wright. Lower fee, more diversified.",
    when: "On correction",
    status: "WAIT",
    corr: "Equity-correlated",
  },
  {
    tier: 2,
    dir: "LONG",
    ticker: "IXJ",
    name: "iShares Global Healthcare",
    type: "Sector ETF",
    fee: "0.40%",
    trends: ["t5", "t8"],
    conv: 82,
    why: "Highest-confidence trend (Demographics 90%). UNH, LLY, ISRG. Most predictable demand curve.",
    when: "On correction",
    status: "WAIT",
    corr: "Low beta",
  },
  {
    tier: 2,
    dir: "LONG",
    ticker: "RARE",
    name: "WisdomTree Strategic Metals & Rare Earths",
    type: "Miners ETF",
    fee: "0.55%",
    trends: ["t3", "t4", "t7"],
    conv: 80,
    why: "Lithium, rare earths, copper miners. Green Mercantilism thesis. Down -17%.",
    when: "Below EUR 38",
    status: "APPROACHING",
    corr: "Equity-correlated",
  },
  {
    tier: 2,
    dir: "LONG",
    ticker: "GDX",
    name: "VanEck Gold Miners ETF",
    type: "Miners ETF",
    fee: "0.51%",
    trends: ["t2", "t7"],
    conv: 78,
    why: "2-3x leverage to gold price. Buy when gold stabilizes from correction.",
    when: "Wait for gold bottom",
    status: "WAIT",
    corr: "Equity-correlated",
  },
  {
    tier: 2,
    dir: "LONG",
    ticker: "W1TB",
    name: "WisdomTree Cybersecurity UCITS",
    type: "Thematic",
    fee: "~0.40%",
    trends: ["t6", "t1"],
    conv: 72,
    why: "Trust Crisis thesis. CRWD, PANW, FTNT. Expensive growth stocks — will crash in tech selloff before recovering.",
    when: "Tech capitulation only",
    status: "WAIT",
    corr: "Equity-correlated",
  },
  {
    tier: 2,
    dir: "LONG",
    ticker: "EUDF",
    name: "VanEck Defence UCITS ETF",
    type: "Sector ETF",
    fee: "0.55%",
    trends: ["t4"],
    conv: 85,
    why: "EU NATO spend on structural 2→3.5→5% of GDP path. RHM, BA.L, LMT, RTX, LHX. 20-year backlog. Highest-visibility capex cycle of the decade.",
    when: "Buy now, accumulate on tech selloffs",
    status: "GO",
    corr: "Equity-correlated",
  },
  {
    tier: 2,
    dir: "LONG",
    ticker: "IQQQ",
    name: "iShares Global Water UCITS",
    type: "Thematic",
    fee: "0.65%",
    trends: ["t11", "t3", "t1", "t5"],
    conv: 80,
    why: "Utility-like compounders (Xylem, Veolia, American Water) with AI/climate tailwinds. Low equity beta. The AI-semi-water convergence is unpriced.",
    when: "On -10% pullback",
    status: "APPROACHING",
    corr: "Low beta",
  },
  {
    tier: 2,
    dir: "LONG",
    ticker: "MOO",
    name: "VanEck Agribusiness ETF",
    type: "Sector ETF",
    fee: "0.53%",
    trends: ["t12", "t4", "t3"],
    conv: 75,
    why: "Deere, Nutrien, Mosaic, Bunge. Fertilizer oligopoly + food weaponization. Trades at cycle-bottom multiples.",
    when: "On correction",
    status: "APPROACHING",
    corr: "Equity-correlated",
  },
  {
    tier: 2,
    dir: "LONG",
    ticker: "IFRA",
    name: "iShares US Infrastructure ETF",
    type: "Sector ETF",
    fee: "0.30%",
    trends: ["t3", "t4", "t1", "t11"],
    conv: 78,
    why: "Broad exposure beyond PWR/ETN individual picks. Grid, water, roads — all backlog-anchored, all capex-cycle beneficiaries.",
    when: "On correction",
    status: "WAIT",
    corr: "Equity-correlated",
  },
];
