import type { Position } from "../../types";

// Tier 4: Long-horizon small-sizing and explicit hedges. Patient capital.

export const TIER_4: Position[] = [
  {
    tier: 4,
    dir: "LONG",
    ticker: "IBIT",
    name: "iShares Bitcoin ETF / 21Shares",
    type: "Crypto",
    fee: "0.25-1.5%",
    trends: ["t2", "t6"],
    conv: 55,
    why: "In theory a hard asset hedge. Currently correlates with risk assets in every selloff.",
    when: "Dollar-cost average, small",
    status: "APPROACHING",
    corr: "Risk-correlated",
  },
  {
    tier: 4,
    dir: "HEDGE",
    ticker: "TAIL",
    name: "Cambria Tail Risk ETF (or SPY puts when VIX<15)",
    type: "Vol/Tail hedge",
    fee: "0.59%",
    trends: ["t1", "t2", "t4"],
    conv: 60,
    why: "Explicit vol buy when VIX is cheap. Bleeds in calm regimes (cost of insurance), crushes in drawdowns. Framework says 'VIX<20 = overweight hedges' — here's the instrument. EU alternative: structured vol products via Avanza.",
    when: "When VIX < 15 (buy insurance cheap)",
    status: "GO",
    corr: "Anti-correlated (tail)",
  },
  {
    tier: 4,
    dir: "SHORT",
    ticker: "KWEB",
    name: "Short China Internet (KWEB) via EU bear certificates",
    type: "Hedge — bear cert",
    fee: "Spread + carry",
    trends: ["t4", "t13"],
    conv: 55,
    why: "Geopolitical fragmentation + China property/demographic decline + tariff overhang. Structurally asymmetric: binary political risk. Use small, EU-listed bear certificate (Avanza Markets) since PRIIPs blocks US inverse ETFs.",
    when: "On every China stimulus-bounce",
    status: "APPROACHING",
    corr: "Anti-correlated to fragmentation risk",
  },
  {
    tier: 4,
    dir: "SHORT",
    ticker: "3TYS",
    name: "Inverse US Treasury 10Y (Leverage Shares 3TYS)",
    type: "Hedge — short duration",
    fee: "0.75%",
    trends: ["t2", "t15"],
    conv: 70,
    why: "Direct expression of the short-bonds debasement thesis. EU-listed. Pays when long-duration sells off. Complements gold (implicit short-bonds) with explicit duration short.",
    when: "When 10Y < 3.75% (cheap entry)",
    status: "APPROACHING",
    corr: "Anti-correlated to duration",
  },
];
