import type { Position } from "../../types";

// Tier 3: Individual high-conviction stocks + country bets. Concentrated, research individually.

export const TIER_3: Position[] = [
  {
    tier: 3,
    dir: "LONG",
    ticker: "CCJ",
    name: "Cameco Corp",
    type: "Stock",
    fee: "-",
    trends: ["t3", "t7"],
    conv: 85,
    why: "Largest Western uranium producer. Real revenue, real production. $2.7B Nuclear Fuel Supply Act contracts.",
    when: "Sector pullback",
    status: "WAIT",
    corr: "Equity-correlated",
  },
  {
    tier: 3,
    dir: "LONG",
    ticker: "NXE",
    name: "NexGen Energy",
    type: "Stock",
    fee: "-",
    trends: ["t3", "t7"],
    conv: 55,
    why: "Highest-grade undeveloped uranium deposit (Rook I). Development-stage, high risk.",
    when: "Very small, speculative only",
    status: "WAIT",
    corr: "Equity-correlated",
  },
  {
    tier: 3,
    dir: "LONG",
    ticker: "XOM",
    name: "Exxon Mobil",
    type: "Stock",
    fee: "-",
    trends: ["t4", "t15", "t7"],
    conv: 72,
    why: "Zero-oil portfolio blindspot. 4% dividend, Guyana + Permian growth, carbon capture optionality. Structural war/fragmentation hedge, real-asset duration.",
    when: "Buy now",
    status: "GO",
    corr: "Low beta vs tech",
  },
  {
    tier: 3,
    dir: "LONG",
    ticker: "DXJ",
    name: "WisdomTree Japan Hedged Equity",
    type: "Country ETF",
    fee: "0.48%",
    trends: ["t5", "t2", "t4"],
    conv: 72,
    why: "Japan is the leading indicator of the US fiscal path (YCC + aging). Corporate reform (TSE buyback push) real. Currency hedge removes yen decay.",
    when: "Accumulate",
    status: "APPROACHING",
    corr: "Equity-correlated",
  },
  {
    tier: 3,
    dir: "LONG",
    ticker: "XYL",
    name: "Xylem Inc",
    type: "Stock",
    fee: "-",
    trends: ["t11", "t3", "t1"],
    conv: 78,
    why: "Pure-play water equipment. Data-center cooling + municipal infra replacement cycle. Recurring aftermarket revenue. High-quality compounder at fair price.",
    when: "On tech-selloff pullback",
    status: "WAIT",
    corr: "Low beta",
  },
  {
    tier: 3,
    dir: "LONG",
    ticker: "NTR",
    name: "Nutrien Ltd",
    type: "Stock",
    fee: "-",
    trends: ["t12", "t4"],
    conv: 70,
    why: "World's largest potash + nitrogen. 5-6x earnings, deep-value. War/fragmentation hedge, food inflation beneficiary.",
    when: "On commodity-fund selling capitulation",
    status: "APPROACHING",
    corr: "Commodity-correlated",
  },
];
